# -*- coding: utf-8 -*-
"""Week1_Task_Puneeth_Nunnapynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NjDw5xU5BtLnf0CQt65hqaam7WRpIw3E

T1: A function that returns the square of a number
"""

def square_a_num():
  data = []
  amount_of_data = int(input("How many numbers do you wish to find the square of?"))
  for i in range(amount_of_data):
    number = int(input("What number do you wish to be squared?"))
    square = number ** 2
    data.append(square)
  print(data)

square_a_num()

"""T2: A function that converts Celsius to Fahrenheit"""

def celsius_to_fahrenheit():
  temp_in_celsius = int(input("Enter a temperature in celsius that you wish to be converted to fahrenheit."))
  # Celsius to Fahrenheit Formula: (°C * 1.8) + 32 = °F -> need to turn this into python syntax
  temp_in_fahrenheit = (temp_in_celsius*1.8) + 32
  print(temp_in_fahrenheit)

celsius_to_fahrenheit()

"""T3: A function that checks whether a number is even or odd"""

def even_odd():
  num = int(input("Enter a number to check for even/odd."))
  if (num % 2 == 0):
    print("Your number is even.")
  else:
    print("Your number is odd.")

even_odd()